apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: backend
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: backend-sta.aditia701.xyz
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: backend-service
            port: 
              number: 4000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: staging
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aditiaipr/backend:latest
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 700m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 400Mi
  